### ISSUE TITLE
On input focus all fields throw error

### ISSUE THREAD

**Issue by christoph-codes** [realim1/todo-log#7]
## Recommendations
 - Run error check on Submit
 - Run individual error handling for each input
<img width="756" alt="Screen Shot 2021-11-22 at 2 04 01 PM" src="https://user-images.githubusercontent.com/54452490/142942114-d5477199-6d62-4fd1-b9e3-38588bba0977.png">

**Comment by realim1** [comment]
@christoph-codes Resolved
